import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/sonner";
import { SessionProvider } from "next-auth/react";
import ProfessionPreload from "@/components/providers/profession-preload";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-heading",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Wendo Health - Connecting You to Trusted Healthcare",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" sizes="any" />
      </head>
      <body
        className={`${inter.variable} ${montserrat.variable} antialiased`}
      >
        <NextTopLoader
          color="#dc2626"
          height={3}
          showSpinner={false}
        />
        
          <main>
            <ProfessionPreload />
            <SessionProvider>
              <TooltipProvider>{children}</TooltipProvider>
            </SessionProvider>
            <Toaster position="top-center" richColors />
          </main>
        
      </body>
    </html>
  );
}
